export const items  = [
    { id: 0, name: "Electronics" },
    { id: 1, name: "Clothing" },
    { id: 2, name: "Home Decor" },
    { id: 3, name: "Food" },
    { id: 4, name: "Sports Gear" },
    { id: 5, name: "Jewelry" },
    { id: 6, name: "Beauty Products" },
    { id: 7, name: "Toys" },
    { id: 8, name: "Books" },
    { id: 9, name: "Fitness" },
    { id: 10, name: "Outdoor" },
    { id: 11, name: "Pets" },
    { id: 12, name: "Art Supplies" },
    { id: 13, name: "furniture" },
    { id: 14, name: "Crafts" },
    { id: 15, name: "Collectibles" },
    { id: 16, name: "Custom Printing" },
    { id: 17, name: "DIY Kits" },
    { id: 18, name: "Gadgets" },
    { id: 19, name: "Accessories" },
    { id: 20, name: "Wellness" },
    { id: 21, name: "Kitchen" },
    { id: 22, name: "Watches" },
    { id: 23, name: "Grocery" },
    { id: 24, name: "Tools" },
    { id: 25, name: "Auto Accessories" },
    { id: 26, name: "Musical Instruments" },
    { id: 27, name: "Kids" },
    { id: 28, name: "Travel" },
    { id: 29, name: "Collectibles" },
    { id: 30, name: "Custom Apparel" },
    { id: 31, name: "Games" },
    { id: 32, name: "Plants" },
    { id: 33, name: "Appliances" },
    { id: 34, name: "Party Supplies" },
    { id: 35, name: "Tea and Coffee" },
    { id: 36, name: "Cycling" },
    { id: 37, name: "Outdoor Furniture" },
    { id: 38, name: "Smart Home" },
    { id: 39, name: "Fashion" },
    { id: 40, name: "Board Games" },
    { id: 41, name: "Gardening" },
    { id: 42, name: "Toys" },
    { id: 43, name: "Tech Repair" },
    { id: 44, name: "Jewelry" },
    { id: 45, name: "Office Supplies" },
    { id: 46, name: "Watches" },
    { id: 47, name: "Subscriptions" },
    { id: 48, name: "Aromatherapy" },
    { id: 49, name: "lights" },
];

items.map(item => item.name.toLocaleLowerCase)
