export const categories = [
  {
    id: 1,
    name: "Electronics",
    description: "Gadgets and tech gear",
    priceRange: "$50 - $2000",
    imageURL: "electronics.webp",
    products: [
      {
        id: 1,
        name: "Apple iPhone 14 Pro 256 GB, Space Black...",
        price: "$100",
        imageURL: "smartphone.jpg",
      },
      {
        id: 2,
        name: "Apple MacBook Air 2020 (8gb,256gb,macOS)...",
        price: "$150",
        imageURL: "laptop.jpg",
      },
      {
        id: 3,
        name: "LG 139 cm (55 inches) 4K Ultra HD Smart LED TV...",
        price: "$80",
        imageURL: "smart tv.webp",
      },
      {
        id: 4,
        name: "Canon EOS 200D II 24.1MP Digital SLR Camera...",
        price: "$120",
        imageURL: "digital camera.jpg",
      },
      {
        id: 5,
        name: "boAt Rockerz 400 Bluetooth On Ear Headphones...",
        price: "$250",
        imageURL: "headphones.jpg",
      },
      {
        id: 6,
        name: "Sony PS4 Slim 500 GB Console...",
        price: "$180",
        imageURL: "gaming-console.jpg",
      },
      {
        id: 7,
        name: "Apple 2022 iPad Air M1 Chip - Space Gray...",
        price: "$90",
        imageURL: "tablet.jpg",
      },
      {
        id: 8,
        name: "Apple Watch Series 9 [GPS 45mm] Smartwatch...",
        price: "$200",
        imageURL: "smart-watch.jpg",
      },
      {
        id: 9,
        name: "Galaxy Buds FE",
        price: "$300",
        imageURL: "earbuds.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "Clothing",
    description: "Fashion for all ages",
    priceRange: "$10 - $500",
    imageURL: "clothing.webp",
    products: [
      {
        id: 1,
        name: "Product 1",
        price: "$50",
        imageURL: "clothing-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$30",
        imageURL: "clothing-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$40",
        imageURL: "clothing-product3.jpg",
      },
      {
        id: 4,
        name: "Product 4",
        price: "$80",
        imageURL: "clothing-product4.jpg",
      },
      {
        id: 5,
        name: "Product 5",
        price: "$70",
        imageURL: "clothing-product5.jpg",
      },
      {
        id: 6,
        name: "Product 6",
        price: "$45",
        imageURL: "clothing-product6.jpg",
      },
      {
        id: 7,
        name: "Product 7",
        price: "$25",
        imageURL: "clothing-product7.jpg",
      },
      {
        id: 8,
        name: "Product 8",
        price: "$60",
        imageURL: "clothing-product8.jpg",
      },
      {
        id: 9,
        name: "Product 9",
        price: "$55",
        imageURL: "clothing-product9.jpg",
      },
    ],
  },
  {
    id: 3,
    name: "Home & Kitchen",
    description: "Household essentials",
    priceRange: "$5 - $500",
    imageURL: "home and kitchen.webp",
    products: [
      {
        id: 1,
        name: "Product 1",
        price: "$20",
        imageURL: "home-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$15",
        imageURL: "home-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$30",
        imageURL: "home-product3.jpg",
      },
      {
        id: 4,
        name: "Product 4",
        price: "$25",
        imageURL: "home-product4.jpg",
      },
      {
        id: 5,
        name: "Product 5",
        price: "$50",
        imageURL: "home-product5.jpg",
      },
      {
        id: 6,
        name: "Product 6",
        price: "$45",
        imageURL: "home-product6.jpg",
      },
      {
        id: 7,
        name: "Product 7",
        price: "$35",
        imageURL: "home-product7.jpg",
      },
      {
        id: 8,
        name: "Product 8",
        price: "$40",
        imageURL: "home-product8.jpg",
      },
      {
        id: 9,
        name: "Product 9",
        price: "$20",
        imageURL: "home-product9.jpg",
      },
    ],
  },
  {
    id: 4,
    name: "Furniture",
    description: "Stylish home furnishings",
    priceRange: "$100 - $2000",
    imageURL: "furniture.png",
    products: [
      {
        id: 1,
        name: "Product 1",
        price: "$1500",
        imageURL: "furniture-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$1800",
        imageURL: "furniture-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$1200",
        imageURL: "furniture-product3.jpg",
      },
      {
        id: 4,
        name: "Product 4",
        price: "$1000",
        imageURL: "furniture-product4.jpg",
      },
      {
        id: 5,
        name: "Product 5",
        price: "$1600",
        imageURL: "furniture-product5.jpg",
      },
      {
        id: 6,
        name: "Product 6",
        price: "$1100",
        imageURL: "furniture-product6.jpg",
      },
      {
        id: 7,
        name: "Product 7",
        price: "$1400",
        imageURL: "furniture-product7.jpg",
      },
      {
        id: 8,
        name: "Product 8",
        price: "$1900",
        imageURL: "furniture-product8.jpg",
      },
      {
        id: 9,
        name: "Product 9",
        price: "$1700",
        imageURL: "furniture-product9.jpg",
      },
    ],
  },
  {
    id: 5,
    name: "Health & Beauty",
    description: "Personal care products",
    priceRange: "$5 - $200",
    imageURL: "health and beauty.webp",
    products: [
      {
        id: 1,
        name: "Product 1",
        price: "$10",
        imageURL: "health-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$15",
        imageURL: "health-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$20",
        imageURL: "health-product3.jpg",
      },
      {
        id: 4,
        name: "Product 4",
        price: "$12",
        imageURL: "health-product4.jpg",
      },
      {
        id: 5,
        name: "Product 5",
        price: "$18",
        imageURL: "health-product5.jpg",
      },
      {
        id: 6,
        name: "Product 6",
        price: "$8",
        imageURL: "health-product6.jpg",
      },
      {
        id: 7,
        name: "Product 7",
        price: "$14",
        imageURL: "health-product7.jpg",
      },
      {
        id: 8,
        name: "Product 8",
        price: "$16",
        imageURL: "health-product8.jpg",
      },
      {
        id: 9,
        name: "Product 9",
        price: "$25",
        imageURL: "health-product9.jpg",
      },
    ],
  },
  {
    id: 6,
    name: "Toys & Games",
    description: "Toys & board games",
    priceRange: "$5 - $200",
    imageURL: "toys.webp",
    products: [
      {
        id: 1,
        name: "Product 1",
        price: "$10",
        imageURL: "toys-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$12",
        imageURL: "toys-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$8",
        imageURL: "toys-product3.jpg",
      },
      {
        id: 4,
        name: "Product 4",
        price: "$15",
        imageURL: "toys-product4.jpg",
      },
      {
        id: 5,
        name: "Product 5",
        price: "$18",
        imageURL: "toys-product5.jpg",
      },
      {
        id: 6,
        name: "Product 6",
        price: "$9",
        imageURL: "toys-product6.jpg",
      },
      {
        id: 7,
        name: "Product 7",
        price: "$14",
        imageURL: "toys-product7.jpg",
      },
      {
        id: 8,
        name: "Product 8",
        price: "$11",
        imageURL: "toys-product8.jpg",
      },
      {
        id: 9,
        name: "Product 9",
        price: "$20",
        imageURL: "toys-product9.jpg",
      },
    ],
  },
  {
    id: 7,
    name: "Sports",
    description: "Gear for active lifestyles",
    priceRange: "$10 - $1000",
    imageURL: "sports.webp",
    products: [
      {
        id: 1,
        name: "Product 1",
        price: "$40",
        imageURL: "sports-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$30",
        imageURL: "sports-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$50",
        imageURL: "sports-product3.jpg",
      },
      {
        id: 4,
        name: "Product 4",
        price: "$70",
        imageURL: "sports-product4.jpg",
      },
      {
        id: 5,
        name: "Product 5",
        price: "$60",
        imageURL: "sports-product5.jpg",
      },
      {
        id: 6,
        name: "Product 6",
        price: "$80",
        imageURL: "sports-product6.jpg",
      },
      {
        id: 7,
        name: "Product 7",
        price: "$90",
        imageURL: "sports-product7.jpg",
      },
      {
        id: 8,
        name: "Product 8",
        price: "$45",
        imageURL: "sports-product8.jpg",
      },
      {
        id: 9,
        name: "Product 9",
        price: "$55",
        imageURL: "sports-product9.jpg",
      },
    ],
  },
  {
    id: 8,
    name: "Jewelry",
    description: "Elegant adornments",
    priceRange: "$20 - $5000",
    imageURL: "jewelry.jpg",
    products: [
      {
        id: 1,
        name: "Product 1",
        price: "$300",
        imageURL: "jewelry-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$250",
        imageURL: "jewelry-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$400",
        imageURL: "jewelry-product3.jpg",
      },
      {
        id: 1,
        name: "Product 1",
        price: "$300",
        imageURL: "jewelry-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$250",
        imageURL: "jewelry-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$400",
        imageURL: "jewelry-product3.jpg",
      },
      {
        id: 1,
        name: "Product 1",
        price: "$300",
        imageURL: "jewelry-product1.jpg",
      },
      {
        id: 2,
        name: "Product 2",
        price: "$250",
        imageURL: "jewelry-product2.jpg",
      },
      {
        id: 3,
        name: "Product 3",
        price: "$400",
        imageURL: "jewelry-product3.jpg",
      },
    ]
  }
]

export const topDeals = [
  {
    id: 1,
    product: "Smart TV",
    price: "$" + (499.99 - 100.0).toFixed(2),
    save: "$" + (100.0).toFixed(2),
    totalAmount: "$499.99",
    imageURL: "smart tv.webp",
  },
  {
    id: 2,
    product: "Laptop",
    price: "$" + (899.0 - 200.0).toFixed(2),
    save: "$" + (200.0).toFixed(2),
    totalAmount: "$899.00",
    imageURL: "laptop.jpg",
  },
  {
    id: 3,
    product: "Designer Watch",
    price: "$" + (199.99 - 50.0).toFixed(2),
    save: "$" + (50.0).toFixed(2),
    totalAmount: "$199.99",
    imageURL: "designer watch.jpg",
  },
  {
    id: 4,
    product: "Headphones",
    price: "$" + (69.99 - 20.0).toFixed(2),
    save: "$" + (20.0).toFixed(2),
    totalAmount: "$69.99",
    imageURL: "headphones.jpg",
  },
  {
    id: 5,
    product: "Kitchen Mixer",
    price: "$" + (129.95 - 30.0).toFixed(2),
    save: "$" + (30.0).toFixed(2),
    totalAmount: "$129.95",
    imageURL: "mixer.jpg",
  },
  {
    id: 6,
    product: "Running Shoes",
    price: "$" + (79.99 - 10.0).toFixed(2),
    save: "$" + (10.0).toFixed(2),
    totalAmount: "$79.99",
    imageURL: "running-shoes.jpg",
  },
  {
    id: 7,
    product: "Smartphone",
    price: "$" + (699.0 - 100.0).toFixed(2),
    save: "$" + (100.0).toFixed(2),
    totalAmount: "$699.00",
    imageURL: "smartphone.jpg",
  },
  {
    id: 8,
    product: "Digital Camera",
    price: "$" + (449.0 - 50.0).toFixed(2),
    save: "$" + (50.0).toFixed(2),
    totalAmount: "$449.00",
    imageURL: "digital camera.jpg",
  },
  {
    id: 9,
    product: "Cookware Set",
    price: "$" + (149.99 - 30.0).toFixed(2),
    save: "$" + (30.0).toFixed(2),
    totalAmount: "$149.99",
    imageURL: "cookware-set.jpg",
  },
  {
    id: 10,
    product: "Coffee Machine",
    price: "$" + (79.95 - 20.0).toFixed(2),
    save: "$" + (20.0).toFixed(2),
    totalAmount: "$79.95",
    imageURL: "coffee machine.jpg",
  },
];

export const trendings = [
  {
    id: 1,
    product: "Smartwatch",
    price: "$149.99",
    save: "$30.00",
    totalAmount: "$179.99",
    imageURL: "smart-watch.jpg",
  },
  {
    id: 2,
    product: "Men's Dress Shoes",
    price: "$79.00",
    save: "$20.00",
    totalAmount: "$99.00",
    imageURL: "mens-dress-shoes.jpg",
  },
  {
    id: 3,
    product: "Gourmet Coffee Set",
    price: "$34.95",
    save: "$10.00",
    totalAmount: "$44.95",
    imageURL: "coffee set.jpg",
  },
  {
    id: 4,
    product: "Fashion Sunglasses",
    price: "$49.99",
    save: "$15.00",
    totalAmount: "$64.99",
    imageURL: "sunglasses.jpg",
  },
  {
    id: 5,
    product: "Wireless Speaker",
    price: "$89.95",
    save: "$25.00",
    totalAmount: "$114.95",
    imageURL: "soundbox.jpg",
  },
  {
    id: 6,
    product: "Luxury Bedding Set",
    price: "$199.99",
    save: "$50.00",
    totalAmount: "$249.99",
    imageURL: "bedding-set.webp",
  },
  {
    id: 7,
    product: "Artisan Chocolate Box",
    price: "$29.99",
    save: "$5.00",
    totalAmount: "$34.99",
    imageURL: "chocolate-box.webp",
  },
  {
    id: 8,
    product: "Women's Sneakers",
    price: "$69.95",
    save: "$15.00",
    totalAmount: "$84.95",
    imageURL: "women's-sneakers.jpg",
  },
  {
    id: 9,
    product: "Portable Espresso Maker",
    price: "$69.00",
    save: "$10.00",
    totalAmount: "$79.00",
    imageURL: "espresso-maker.jpg",
  },
  {
    id: 10,
    product: "Outdoor Camping Gear",
    price: "$249.99",
    save: "$40.00",
    totalAmount: "$289.99",
    imageURL: "camping-gear.jpg",
  },
];

export const recommendedProducts = [
  {
    id: 1,
    product: "Gaming Console",
    price: 499.99,
    save: 50.0,
    totalAmount: 549.99,
    imageURL: "gaming-console.jpg",
  },
  {
    id: 2,
    product: "Noise-Cancel Earbuds",
    price: 249.0,
    save: 30.0,
    totalAmount: 279.0,
    imageURL: "earbuds.jpg",
  },
  {
    id: 3,
    product: "Chef's Knife Set",
    price: 149.95,
    save: 25.0,
    totalAmount: "174.95",
    imageURL: "knife-set.jpg",
  },
  {
    id: 4,
    product: "Travel Backpack",
    price: "79.99",
    save: "10.00",
    totalAmount: "89.99",
    imageURL: "backpack.jpg",
  },
  {
    id: 5,
    product: "Smart Thermostat",
    price: "149.00",
    save: "20.00",
    totalAmount: "169.00",
    imageURL: "smart-thermostat.jpg",
  },
  {
    id: 6,
    product: "Designer Sunglasses",
    price: "169.99",
    save: "30.00",
    totalAmount: "199.99",
    imageURL: "designer-sunglasses.jpg",
  },
  {
    id: 7,
    product: "Portable Outdoor Grill",
    price: "129.00",
    save: "15.00",
    totalAmount: "144.00",
    imageURL: "portable-grill.jpg",
  },
  {
    id: 8,
    product: "Camera System",
    price: "299.99",
    save: "50.00",
    totalAmount: "349.99",
    imageURL: "security-camera.jpg",
  },
  {
    id: 9,
    product: "Luxurious Velvet Sofa",
    price: "799.00",
    save: "100.00",
    totalAmount: "899.00",
    imageURL: "velvet sofa.jpg",
  },
  {
    id: 10,
    product: "Digital Drawing Tablet",
    price: "199.99",
    save: "30.00",
    totalAmount: "229.99",
    imageURL: "drawing-tablet.jpg",
  },
];
