export const categories = [
  {
    id: 1,
    name: "Electronics",
    description: "Gadgets and tech gear",
    priceRange: "$50 - $2000",
    imageURL: "electronics.webp",
    products: [
      {
        id: 1,
        name: "Apple iPhone 14 Pro 256 GB, Space Black",
        price: "$100",
        imageURL: "smartphone.jpg",
      },
      {
        id: 2,
        name: "Apple MacBook Air 2020 (8gb,256gb,macOS)",
        price: "$150",
        imageURL: "laptop.jpg",
      },
      {
        id: 3,
        name: "LG 139 cm (55 inches) 4K Ultra HD Smart LED TV",
        price: "$80",
        imageURL: "smart tv.webp",
      },
      {
        id: 4,
        name: "Canon EOS 200D II 24.1MP Digital SLR Camera",
        price: "$120",
        imageURL: "digital camera.jpg",
      },
      {
        id: 5,
        name: "boAt Rockerz 400 Bluetooth On Ear Headphones",
        price: "$250",
        imageURL: "headphones.jpg",
      },
      {
        id: 6,
        name: "Sony PS4 Slim 500 GB Console",
        price: "$180",
        imageURL: "gaming-console.jpg",
      },
      {
        id: 7,
        name: "Apple 2022 iPad Air M1 Chip - Space Gray",
        price: "$90",
        imageURL: "tablet.jpg",
      },
      {
        id: 8,
        name: "Apple Watch Series 9 [GPS 45mm] Smartwatch",
        price: "$200",
        imageURL: "smart-watch.jpg",
      },
      {
        id: 9,
        name: "Galaxy Buds FE",
        price: "$300",
        imageURL: "earbuds.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "Clothing",
    description: "Fashion for all ages",
    priceRange: "$10 - $500",
    imageURL: "clothing.webp",
    products: [
      {
        id: 1,
        name: "T-shirt",
        price: "$20",
        imageURL: "t-shirt.webp",
      },
      {
        id: 2,
        name: "Jeans",
        price: "$30",
        imageURL: "jeans.webp",
      },
      {
        id: 3,
        name: "Dress",
        price: "$50",
        imageURL: "dress.webp",
      },
      {
        id: 4,
        name: "Sweater",
        price: "$40",
        imageURL: "sweater.webp",
      },
      {
        id: 5,
        name: "Shorts",
        price: "$25",
        imageURL: "shorts.webp",
      },
      {
        id: 6,
        name: "Jacket",
        price: "$60",
        imageURL: "jacket.webp",
      },
      {
        id: 7,
        name: "Skirt",
        price: "$35",
        imageURL: "skirt.webp",
      },
      {
        id: 8,
        name: "Blouse",
        price: "$30",
        imageURL: "shoes.webp",
      },
      {
        id: 9,
        name: "Pants",
        price: "$40",
        imageURL: "pants.webp",
      },
      {
        id: 10,
        name: "Hoodie",
        price: "$45",
        imageURL: "hoodie.webp",
      },
    ],
  },
  {
    id: 3,
    name: "Home & Kitchen",
    description: "Household essentials",
    priceRange: "$5 - $500",
    imageURL: "home and kitchen.webp",
    products: [
      {
        id: 1,
        name: "Stainless Steel Cookware Set (10 Pieces)",
        price: "$100",
        imageURL: "steel-cookware-set.jpg",
      },
      {
        id: 2,
        name: "Coffee Maker with Grinder",
        price: "$50",
        imageURL: "coffee-maker2.jpg",
      },
      {
        id: 3,
        name: "Non-Stick Frying Pan",
        price: "$20",
        imageURL: "non-sticky-frying-pan.jpg",
      },
      {
        id: 4,
        name: "Slow Cooker (6 Quart)",
        price: "$40",
        imageURL: "slow-cooker.jpg",
      },
      {
        id: 5,
        name: "Dinnerware Set (16 Pieces)",
        price: "$30",
        imageURL: "dinnerware.jpg",
      },
      {
        id: 6,
        name: "Blender with Glass Jar",
        price: "$35",
        imageURL: "blender.jpg",
      },
      {
        id: 7,
        name: "Cutlery Set (20 Pieces)",
        price: "$25",
        imageURL: "cutlery.jpg",
      },
      {
        id: 8,
        name: "Toaster Oven",
        price: "$40",
        imageURL: "toaster_oven.jpg",
      },
      {
        id: 9,
        name: "Vacuum Cleaner (Cordless)",
        price: "$60",
        imageURL: "vacuum_cleaner.jpg",
      },
      {
        id: 10,
        name: "Microwave Oven (1.1 cu. ft.)",
        price: "$70",
        imageURL: "microwave_oven.jpg",
      },
    ],
  },
  {
    id: 4,
    name: "Furniture",
    description: "Stylish home furnishings",
    priceRange: "$100 - $2000",
    imageURL: "furniture.png",
    products: [
      {
        id: 1,
        name: "Sofa with Chaise Lounge",
        price: "$600",
        imageURL: "sofa.jpg",
      },
      {
        id: 2,
        name: "Dining Table with 6 Chairs",
        price: "$450",
        imageURL: "dining_table.jpg",
      },
      {
        id: 3,
        name: "Queen Size Bed with Mattress",
        price: "$700",
        imageURL: "bed.jpg",
      },
      {
        id: 4,
        name: "Coffee Table with Storage",
        price: "$150",
        imageURL: "coffee_table.jpg",
      },
      {
        id: 5,
        name: "Bookshelf (5-Tier)",
        price: "$80",
        imageURL: "bookshelf.jpg",
      },
      {
        id: 6,
        name: "Wardrobe Closet",
        price: "$300",
        imageURL: "wardrobe.jpg",
      },
      {
        id: 7,
        name: "Computer Desk with Hutch",
        price: "$200",
        imageURL: "computer_desk.jpg",
      },
      {
        id: 8,
        name: "Recliner Chair",
        price: "$250",
        imageURL: "recliner_chair.jpg",
      },
      {
        id: 9,
        name: "Nightstand with Drawers",
        price: "$50",
        imageURL: "nightstand.jpg",
      },
      {
        id: 10,
        name: "TV Stand with Storage",
        price: "$120",
        imageURL: "tv_stand.jpg",
      },
    ],
  },
  {
    id: 5,
    name: "Health & Beauty",
    description: "Personal care products",
    priceRange: "$5 - $200",
    imageURL: "health and beauty.webp",
    products: [
      {
        id: 1,
        name: "Electric Toothbrush",
        price: "$50",
        imageURL: "toothbrush.jpg",
      },
      {
        id: 2,
        name: "Facial Cleansing Brush",
        price: "$30",
        imageURL: "facial_cleansing_brush.jpg",
      },
      {
        id: 3,
        name: "Hair Dryer with Ionic Technology",
        price: "$40",
        imageURL: "hair_dryer.jpg",
      },
      {
        id: 4,
        name: "Makeup Kit (Eyeshadow Palette)",
        price: "$25",
        imageURL: "makeup_palette.jpg",
      },
      {
        id: 5,
        name: "Shampoo and Conditioner Set",
        price: "$20",
        imageURL: "shampoo_conditioner.jpg",
      },
      {
        id: 6,
        name: "Handheld Massager",
        price: "$35",
        imageURL: "massager.jpg",
      },
      {
        id: 7,
        name: "Sunscreen (SPF 30)",
        price: "$15",
        imageURL: "sunscreen.jpg",
      },
      {
        id: 8,
        name: "Men's Grooming Kit",
        price: "$60",
        imageURL: "grooming_kit.jpg",
      },
      {
        id: 9,
        name: "Nail Polish Set (10 Colors)",
        price: "$20",
        imageURL: "nail_polish.jpg",
      },
      {
        id: 10,
        name: "Fragrance (Eau de Parfum)",
        price: "$50",
        imageURL: "perfume.jpg",
      },
    ],
  },
  {
    id: 6,
    name: "Toys & Games",
    description: "Toys & board games",
    priceRange: "$5 - $200",
    imageURL: "toys.webp",
    products: [
      {
        id: 1,
        name: "LEGO Classic Creative Bricks Set",
        price: "$25",
        imageURL: "lego.jpg",
      },
      {
        id: 2,
        name: "Board Game - Settlers of Catan",
        price: "$35",
        imageURL: "board_game.jpg",
      },
      {
        id: 3,
        name: "Barbie Dreamhouse Playset",
        price: "$75",
        imageURL: "barbie_dreamhouse.jpg",
      },
      {
        id: 4,
        name: "Video Game Console (PlayStation 5)",
        price: "$500",
        imageURL: "ps5.jpg",
      },
      {
        id: 5,
        name: "Remote Control Car",
        price: "$40",
        imageURL: "rc_car.jpg",
      },
      {
        id: 6,
        name: "Puzzle - 1000 Pieces",
        price: "$20",
        imageURL: "puzzle.jpg",
      },
      {
        id: 7,
        name: "Action Figure - Superhero",
        price: "$15",
        imageURL: "action_figure.jpg",
      },
      {
        id: 8,
        name: "Dollhouse with Furniture",
        price: "$50",
        imageURL: "dollhouse.jpg",
      },
      {
        id: 9,
        name: "Outdoor Playset - Swing and Slide",
        price: "$200",
        imageURL: "playset.jpg",
      },
      {
        id: 10,
        name: "Board Game - Chess Set",
        price: "$15",
        imageURL: "chess_set.jpg",
      },
    ],
  },
  {
    id: 7,
    name: "Sports",
    description: "Gear for active lifestyles",
    priceRange: "$10 - $1000",
    imageURL: "sports.webp",
    products: [
      {
        id: 1,
        name: "Basketball",
        price: "$20",
        imageURL: "basketball.jpg",
      },
      {
        id: 2,
        name: "Tennis Racket",
        price: "$50",
        imageURL: "tennis_racket.jpg",
      },
      {
        id: 3,
        name: "Soccer Ball",
        price: "$15",
        imageURL: "soccer_ball.jpg",
      },
      {
        id: 4,
        name: "Golf Club Set",
        price: "$200",
        imageURL: "golf_clubs.jpg",
      },
      {
        id: 5,
        name: "Yoga Mat",
        price: "$20",
        imageURL: "yoga_mat.jpg",
      },
      {
        id: 6,
        name: "Running Shoes",
        price: "$80",
        imageURL: "running_shoes.jpg",
      },
      {
        id: 7,
        name: "Cycling Helmet",
        price: "$30",
        imageURL: "cycling_helmet.jpg",
      },
      {
        id: 8,
        name: "Boxing Gloves",
        price: "$40",
        imageURL: "boxing_gloves.jpg",
      },
      {
        id: 9,
        name: "Fitness Tracker Watch",
        price: "$60",
        imageURL: "fitness_tracker.jpg",
      },
      {
        id: 10,
        name: "Swimming Goggles",
        price: "$15",
        imageURL: "swimming_goggles.jpg",
      },
    ],
  },
  {
    id: 8,
    name: "Jewelry",
    description: "Elegant adornments",
    priceRange: "$20 - $5000",
    imageURL: "jewelry.jpg",
    products: [
      {
        id: 1,
        name: "Diamond Engagement Ring",
        price: "$3,000",
        imageURL: "engagement_ring.jpg",
      },
      {
        id: 2,
        name: "Pearl Necklace",
        price: "$200",
        imageURL: "pearl_necklace.jpg",
      },
      {
        id: 3,
        name: "Gold Hoop Earrings",
        price: "$100",
        imageURL: "hoop_earrings.jpg",
      },
      {
        id: 4,
        name: "Silver Bracelet",
        price: "$50",
        imageURL: "silver_bracelet.jpg",
      },
      {
        id: 5,
        name: "Sapphire Pendant",
        price: "$150",
        imageURL: "sapphire_pendant.jpg",
      },
      {
        id: 6,
        name: "Emerald Ring",
        price: "$250",
        imageURL: "emerald_ring.jpg",
      },
      {
        id: 7,
        name: "Ruby Earrings",
        price: "$120",
        imageURL: "ruby_earrings.jpg",
      },
      {
        id: 8,
        name: "Men's Titanium Ring",
        price: "$80",
        imageURL: "titanium_ring.jpg",
      },
      {
        id: 9,
        name: "Crystal Brooch",
        price: "$30",
        imageURL: "crystal_brooch.jpg",
      },
      {
        id: 10,
        name: "Rose Gold Bangle",
        price: "$70",
        imageURL: "rose_gold_bangle.jpg",
      },
    ],
  },
];

export const topDeals = [
  {
    id: 1,
    product: "Smart TV",
    price: "$" + (499.99 - 100.0).toFixed(2),
    save: "$" + (100.0).toFixed(2),
    totalAmount: "$499.99",
    imageURL: "smart tv.webp",
  },
  {
    id: 2,
    product: "Laptop",
    price: "$" + (899.0 - 200.0).toFixed(2),
    save: "$" + (200.0).toFixed(2),
    totalAmount: "$899.00",
    imageURL: "laptop.jpg",
  },
  {
    id: 3,
    product: "Designer Watch",
    price: "$" + (199.99 - 50.0).toFixed(2),
    save: "$" + (50.0).toFixed(2),
    totalAmount: "$199.99",
    imageURL: "designer watch.jpg",
  },
  {
    id: 4,
    product: "Headphones",
    price: "$" + (69.99 - 20.0).toFixed(2),
    save: "$" + (20.0).toFixed(2),
    totalAmount: "$69.99",
    imageURL: "headphones.jpg",
  },
  {
    id: 5,
    product: "Kitchen Mixer",
    price: "$" + (129.95 - 30.0).toFixed(2),
    save: "$" + (30.0).toFixed(2),
    totalAmount: "$129.95",
    imageURL: "mixer.jpg",
  },
  {
    id: 6,
    product: "Running Shoes",
    price: "$" + (79.99 - 10.0).toFixed(2),
    save: "$" + (10.0).toFixed(2),
    totalAmount: "$79.99",
    imageURL: "running-shoes.jpg",
  },
  {
    id: 7,
    product: "Smartphone",
    price: "$" + (699.0 - 100.0).toFixed(2),
    save: "$" + (100.0).toFixed(2),
    totalAmount: "$699.00",
    imageURL: "smartphone.jpg",
  },
  {
    id: 8,
    product: "Digital Camera",
    price: "$" + (449.0 - 50.0).toFixed(2),
    save: "$" + (50.0).toFixed(2),
    totalAmount: "$449.00",
    imageURL: "digital camera.jpg",
  },
  {
    id: 9,
    product: "Cookware Set",
    price: "$" + (149.99 - 30.0).toFixed(2),
    save: "$" + (30.0).toFixed(2),
    totalAmount: "$149.99",
    imageURL: "cookware-set.jpg",
  },
  {
    id: 10,
    product: "Coffee Machine",
    price: "$" + (79.95 - 20.0).toFixed(2),
    save: "$" + (20.0).toFixed(2),
    totalAmount: "$79.95",
    imageURL: "coffee machine.jpg",
  },
];

export const trendings = [
  {
    id: 1,
    product: "Smartwatch",
    price: "$149.99",
    save: "$30.00",
    totalAmount: "$179.99",
    imageURL: "smart-watch.jpg",
  },
  {
    id: 2,
    product: "Men's Dress Shoes",
    price: "$79.00",
    save: "$20.00",
    totalAmount: "$99.00",
    imageURL: "mens-dress-shoes.jpg",
  },
  {
    id: 3,
    product: "Gourmet Coffee Set",
    price: "$34.95",
    save: "$10.00",
    totalAmount: "$44.95",
    imageURL: "coffee set.jpg",
  },
  {
    id: 4,
    product: "Fashion Sunglasses",
    price: "$49.99",
    save: "$15.00",
    totalAmount: "$64.99",
    imageURL: "sunglasses.jpg",
  },
  {
    id: 5,
    product: "Wireless Speaker",
    price: "$89.95",
    save: "$25.00",
    totalAmount: "$114.95",
    imageURL: "soundbox.jpg",
  },
  {
    id: 6,
    product: "Luxury Bedding Set",
    price: "$199.99",
    save: "$50.00",
    totalAmount: "$249.99",
    imageURL: "bedding-set.webp",
  },
  {
    id: 7,
    product: "Artisan Chocolate Box",
    price: "$29.99",
    save: "$5.00",
    totalAmount: "$34.99",
    imageURL: "chocolate-box.webp",
  },
  {
    id: 8,
    product: "Women's Sneakers",
    price: "$69.95",
    save: "$15.00",
    totalAmount: "$84.95",
    imageURL: "women's-sneakers.jpg",
  },
  {
    id: 9,
    product: "Portable Espresso Maker",
    price: "$69.00",
    save: "$10.00",
    totalAmount: "$79.00",
    imageURL: "espresso-maker.jpg",
  },
  {
    id: 10,
    product: "Outdoor Camping Gear",
    price: "$249.99",
    save: "$40.00",
    totalAmount: "$289.99",
    imageURL: "camping-gear.jpg",
  },
];

export const recommendedProducts = [
  {
    id: 1,
    product: "Gaming Console",
    price: 499.99,
    save: 50.0,
    totalAmount: 549.99,
    imageURL: "gaming-console.jpg",
  },
  {
    id: 2,
    product: "Noise-Cancel Earbuds",
    price: 249.0,
    save: 30.0,
    totalAmount: 279.0,
    imageURL: "earbuds.jpg",
  },
  {
    id: 3,
    product: "Chef's Knife Set",
    price: 149.95,
    save: 25.0,
    totalAmount: "174.95",
    imageURL: "knife-set.jpg",
  },
  {
    id: 4,
    product: "Travel Backpack",
    price: "79.99",
    save: "10.00",
    totalAmount: "89.99",
    imageURL: "backpack.jpg",
  },
  {
    id: 5,
    product: "Smart Thermostat",
    price: "149.00",
    save: "20.00",
    totalAmount: "169.00",
    imageURL: "smart-thermostat.jpg",
  },
  {
    id: 6,
    product: "Designer Sunglasses",
    price: "169.99",
    save: "30.00",
    totalAmount: "199.99",
    imageURL: "designer-sunglasses.jpg",
  },
  {
    id: 7,
    product: "Portable Outdoor Grill",
    price: "129.00",
    save: "15.00",
    totalAmount: "144.00",
    imageURL: "portable-grill.jpg",
  },
  {
    id: 8,
    product: "Camera System",
    price: "299.99",
    save: "50.00",
    totalAmount: "349.99",
    imageURL: "security-camera.jpg",
  },
  {
    id: 9,
    product: "Luxurious Velvet Sofa",
    price: "799.00",
    save: "100.00",
    totalAmount: "899.00",
    imageURL: "velvet sofa.jpg",
  },
  {
    id: 10,
    product: "Digital Drawing Tablet",
    price: "199.99",
    save: "30.00",
    totalAmount: "229.99",
    imageURL: "drawing-tablet.jpg",
  },
];
